#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: elasticsearch
#  labels:
#    type: local
#spec:
#  storageClassName: local-pvdata
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteMany
#  hostPath:
#    path: "/mnt/pvdata"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
spec:
  storageClassName: nfs
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /mnt/pvdata
    server: 172.31.43.227